const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const [content,analysis,contract]=await Promise.all([
  fetch('../../api/content-index.v1.json',{cache:'no-store'}).then(r=>r.json()),
  fetch('../../api/content-analysis.v1.json',{cache:'no-store'}).then(r=>r.json()),
  fetch('../../api/component-catalog.v1.json',{cache:'no-store'}).then(r=>r.json())
]);
const analysisByContent=new Map(analysis.items.map(item=>[item.content_id,item]));
const state={items:content.items,components:contract.components};
function option(select,values,label){[...new Set(values.filter(Boolean))].sort().forEach(value=>select.add(new Option(label[value]||value,value)))}
option($('typeFilter'),state.items.map(x=>x.content_type),{quote:'Quote',story:'Story',knowledge_insight:'Knowledge / Insight'});
option($('formatFilter'),state.items.map(x=>x.reader_format),{});
option($('themeFilter'),state.items.map(x=>x.primary_theme),{});
function metrics(){const types=content.summary.by_content_type;$('contentSummary').innerHTML=`<article class="metric"><strong>${content.summary.total}</strong><span>Tổng content</span></article><article class="metric"><strong>${types.quote||0}</strong><span>Quote</span></article><article class="metric"><strong>${types.story||0}</strong><span>Story</span></article><article class="metric"><strong>${types.knowledge_insight||0}</strong><span>Knowledge / Insight</span></article>`}
function tags(values){return (values||[]).filter(Boolean).map(value=>`<span class="pill">${esc(value)}</span>`).join('')||'—'}
function renderContent(){
  const q=$('contentSearch').value.trim().toLocaleLowerCase('vi'),type=$('typeFilter').value,format=$('formatFilter').value,theme=$('themeFilter').value;
  const rows=state.items.filter(item=>(type==='all'||item.content_type===type)&&(format==='all'||item.reader_format===format)&&(theme==='all'||item.primary_theme===theme)&&(!q||[item.id,item.title_vi,item.text_vi,item.subtitle_vi,item.search_document_vi,...(item.keywords||[])].join(' ').toLocaleLowerCase('vi').includes(q)));
  $('contentRows').innerHTML=rows.length?rows.map(item=>{const companion=analysisByContent.get(item.id);return `<tr><td><h3>${esc(item.title_vi||item.text_vi)}</h3><code>${esc(item.id)}</code><div>${esc(item.subtitle_vi||'')}</div></td><td><span class="pill ${item.content_type==='knowledge_insight'?'knowledge':'story'}">${esc(item.content_type_label_vi)}</span><div><code>${esc(item.classification_source)}</code></div></td><td><code>${esc(item.runtime_entity)}</code><div>${esc(item.reader_format)}</div><div>schema ${esc(item.schema_version)} · r${item.revision}</div></td><td>${tags([item.primary_theme,item.story_style])}</td><td>${tags([item.status,item.review_status,item.rights_status])}</td><td class="cell-list"><b>Keywords</b><br>${tags(item.keywords)}<br><b>Concepts</b><br>${tags(item.concept_ids)}</td><td class="cell-list">${Object.entries(item.block_inventory||{}).map(([key,count])=>`<span class="pill">${esc(key)} × ${count}</span>`).join('')||'—'}</td><td class="cell-list">${companion?`<span class="pill knowledge">${esc(companion.editorial_assessment.depth_status)}</span><div>${esc(companion.editorial_assessment.summary_vi)}</div>`:'—'}</td><td>${item.reader_url?`<a class="open" href="${esc(item.reader_url)}">Đọc</a>`:'—'}</td></tr>`}).join(''):`<tr><td colspan="9" class="empty">Không có content phù hợp.</td></tr>`;
}
function preview(item){const id=item.id;let body='<p>Một đoạn nội dung giúp ý tưởng được đọc liền mạch và rõ ràng.</p>';if(id.includes('quote'))body='<blockquote>“Một câu cần được dừng lại lâu hơn.”</blockquote>';else if(id.includes('heading'))body='<span>PHẦN 02</span><h4>Một chuyển ý rõ ràng</h4>';else if(id.includes('list'))body='<ul><li>Ý thứ nhất</li><li>Ý thứ hai</li></ul>';else if(id.includes('statement'))body='<strong>Thông điệp cốt lõi được nhấn vừa đủ.</strong>';else if(id.includes('reflection'))body='<em>Điều gì đang khiến mình im lặng?</em>';else if(id.includes('flow'))body='<div class="mini-flow">Nhận ra <b>→</b> Dừng lại <b>→</b> Chọn</div>';else if(id.includes('aside'))body='<small>Giới hạn: bằng chứng này không cho phép kết luận cho mọi trường hợp.</small>';else if(id==='rich_text')body='<p>Đây là narrative có <strong>từ khóa quan trọng</strong> ngay trong câu.</p>';return `<div class="component-preview" data-kind="${esc(id)}"><div class="mini-phone">${body}</div><div class="mini-web">${body}</div></div>`}
function renderContract(){const q=$('componentSearch').value.trim().toLocaleLowerCase('vi');const rows=state.components.filter(item=>!q||Object.values(item).join(' ').toLocaleLowerCase('vi').includes(q));$('componentGrid').innerHTML=rows.length?rows.map(item=>`<article class="component"><div class="component-name"><span class="pill">${esc(item.family)}</span><h3>${esc(item.label_vi)}</h3><code>${esc(item.wire_selector)}</code></div>${preview(item)}<dl><dt>Ý nghĩa</dt><dd>${esc(item.meaning_vi)}</dd><dt>Nên dùng</dt><dd>${esc(item.use_when_vi)}</dd><dt>Tránh</dt><dd>${esc(item.avoid_vi)}</dd><dt>Web</dt><dd>${esc(item.web_ui_vi)}</dd><dt>App</dt><dd>${esc(item.app_ui_vi)}</dd></dl><div class="support">${Object.entries(item.support||{}).map(([key,value])=>`<span class="pill">${esc(key.replace('_status',''))}: ${esc(value||'—')}</span>`).join('')}</div></article>`).join(''):`<p class="empty">Không có component phù hợp.</p>`}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));$('contentPanel').hidden=button.dataset.tab!=='content';$('contractPanel').hidden=button.dataset.tab!=='contract'});
['contentSearch','typeFilter','formatFilter','themeFilter'].forEach(id=>$(id).addEventListener('input',renderContent));
$('componentSearch').addEventListener('input',renderContract);metrics();renderContent();renderContract();
