window.ChunkContent.register({schemaVersion:2,session:{id:"daily-07-work",title:"Work and collaboration",dates:["2026-09-25"],topics:["work","collaboration"],level:"B1"},items:[
["work-started","I'll get started.","/aɪl ɡet ˈstɑːrtɪd/","ail-ghét-STA-tịt","I will begin now.","Accept a task and begin it."],
["work-on-it","I'm working on it.","/aɪm ˈwɝːkɪŋ ɑːn ɪt/","aim-UƠ-king-on-ịt","The task is currently in progress.","Give a quick status update."],
["work-done","I'm almost done.","/aɪm ˈɔːlmoʊst dʌn/","aim-OL-mâust-đân","The task is nearly complete.","Someone asks when you will finish."],
["work-finished","I've finished it.","/aɪv ˈfɪnɪʃt ɪt/","aiv-FI-nịsht-ịt","The task is complete.","Report completion."],
["work-review","It's ready for review.","/ɪts ˈredi fər rɪˈvjuː/","ịts-RÉ-đi-phờ-ri-VIU","Someone can review it now.","Hand work to a teammate."],
["work-feedback","I'd appreciate your feedback.","/aɪd əˈpriːʃieɪt jər ˈfiːdbæk/","aiđ-ờ-PRI-shi-âyt-dờ-FIĐ-béc","I would value your comments.","Ask someone to review your work."],
["work-change","I'll make the changes.","/aɪl meɪk ðə ˈtʃeɪndʒɪz/","ail-mâyk-đờ-CHÂYN-jịt","I will apply the requested edits.","Respond to review feedback."],
["work-update","I'll keep you posted.","/aɪl kiːp ju ˈpoʊstɪd/","ail-kip-du-PÂUS-tịt","I will continue giving you updates.","Promise ongoing communication."],
["work-blocked","I'm blocked on this.","/aɪm blɑːkt ɑːn ðɪs/","aim-blókt-on-ĐIS","Something prevents me from progressing.","Report a work obstacle."],
["work-need-input","I need your input.","/aɪ niːd jər ˈɪnpʊt/","ai-niđ-dờ-IN-pút","I need your opinion or information.","You cannot decide alone."],
["work-take-over","Can you take over?","/kæn ju teɪk ˈoʊvər/","ken-du-tâyk-ÂU-vờ","Can you assume responsibility?","You need another person to continue the task."],
["work-handle","I can handle it.","/aɪ kæn ˈhændəl ɪt/","ai-ken-HEN-đồ-lịt","I am able to manage this.","Volunteer for a task."],
["work-help-out","Thanks for helping out.","/θæŋks fər ˈhelpɪŋ aʊt/","théngks-phờ-HEL-ping-ao","Thank you for providing help.","Show gratitude to a teammate."],
["work-team-effort","It was a team effort.","/ɪt wəz ə tiːm ˈefərt/","ịt-uờz-ờ-tim-É-phờt","Several people contributed.","Share credit after success."],
["work-owner","Who's the owner of this?","/huːz ði ˈoʊnər əv ðɪs/","huz-đi-ÂU-nờ-rờv-đis","Who is responsible for this?","Find the right contact person."],
["work-assign","I'll assign it to you.","/aɪl əˈsaɪn ɪt tə ju/","ail-ờ-SAIN-ịt-tờ-du","I will make you responsible for it.","Delegate a task."],
["work-split","Let's split the work.","/lets splɪt ðə wɝːk/","léts-splịt-đờ-UƠK","Let's divide the task.","Collaborate on a large task."],
["work-focus","Let's focus on the main issue.","/lets ˈfoʊkəs ɑːn ðə meɪn ˈɪʃuː/","léts-PHÂU-cợs-on-đờ-mâyn-I-shu","Let's prioritize the central problem.","A discussion is drifting."],
["work-scope","That's outside the scope.","/ðæts ˌaʊtˈsaɪd ðə skoʊp/","đéts-ao-SAIĐ-đờ-scâup","That is not included in this work.","Clarify project boundaries."],
["work-requirement","What's the requirement?","/wʌts ðə rɪˈkwaɪərmənt/","uấts-đờ-ri-KWAI-ờ-mần","What must the solution do?","Clarify expected behavior."],
["work-goal","What's the goal here?","/wʌts ðə ɡoʊl hɪr/","uấts-đờ-gâul-HIA","What outcome are we trying to achieve?","Align before starting work."],
["work-practical","Let's keep it simple.","/lets kiːp ɪt ˈsɪmpəl/","léts-kip-ịt-SIM-pồ","Let's avoid unnecessary complexity.","Choose a practical approach."],
["work-document","Please document this.","/pliːz ˈdɑːkjument ðɪs/","pliz-ĐÓ-kiu-men-đis","Please write down how this works.","Preserve knowledge for the team."],
["work-share","I'll share the details.","/aɪl ʃer ðə ˈdiːteɪlz/","ail-she-đờ-ĐI-tâylz","I will provide the information.","Promise follow-up information."],
["work-access","I don't have access.","/aɪ doʊnt hæv ˈækses/","ai-đâunt-hav-ÉK-ses","I lack permission to use it.","Explain why you cannot proceed."],
["work-permission","Can you give me access?","/kæn ju ɡɪv mi ˈækses/","ken-du-ghiv-mi-ÉK-ses","Please grant me permission.","Request access to a tool or file."],
["work-check-team","I'll check with the team.","/aɪl tʃek wɪð ðə tiːm/","ail-chék-uýt-đờ-TIM","I will ask the team before answering.","You need collective input."],
["work-circle-back","Let's circle back later.","/lets ˈsɝːkəl bæk ˈleɪtər/","léts-SƠ-cồ-béc-LÂY-tờ","Let's return to this topic later.","Defer a discussion."],
["work-follow-up","I'll follow up tomorrow.","/aɪl ˈfɑːloʊ ʌp təˈmɑːroʊ/","ail-FA-lâu-ấp-tờ-MO-râu","I will contact you about this tomorrow.","Set an expected next communication."],
["work-good-job","Nice work on this.","/naɪs wɝːk ɑːn ðɪs/","nais-uơk-on-ĐIS","You did this well.","Compliment a colleague's work."]
]});
